# Firebase Hosting Deployment Workflow

name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Move to Correct Directory (If Needed)
        run: |
          if [ -d "trackify/trackify" ]; then
            mv trackify/trackify/* trackify/
            rm -rf trackify/trackify
          fi
        shell: bash

      - name: Install Dependencies
        run: npm install
        working-directory: ./trackify

      - name: Build Project
        run: npm run build
        working-directory: ./trackify 

      - name: Deploy to Firebase Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKIFY_3140 }}
          projectId: trackify-3140
          entryPoint: ./trackify